### ISSUE TITLE
tidyer rounding p-values

### ISSUE THREAD

**Issue by mcjmigdal** [junkka/ehahelper#2]
Hi,

I've found that `tidy.coxme` function is internally rounding p-values and estimates to first 3 numbers. To me it is undesirable behavior as one might lose precision upon further processing of the results. 

Cheers MM

**Comment by mcjmigdal** [comment]
I've forked `ehahelper` and makde PR #3 that fixes this. If you agree that it makes sense you could merge it if not fell free to close this issue.

**Comment by junkka** [comment]
Yes rounding is not ideal. I'll merge the PR. Thank you.
